SistemaAC/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaAC.Data;
using SistemaAC.Models;
using SistemaAC.ModelsClass;
using Microsoft.AspNetCore.Identity;
using SistemaAC.Negocio.Categoria.Fachada;

namespace SistemaAC.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ICategoriaFachada categoriaFachada;

        public CategoriasController(ApplicationDbContext context)
        {
            _context = context;
            categoriaFachada = new CategoriaFachada(_context);
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public List<object[]> filtrarDatos(int numPagina, string valor, string order)
        {
            return categoriaFachada.filtrarDatos(numPagina, valor, order);
        }
        public List<Categoria> getCategorias(int id)
        {
            return categoriaFachada.getCategorias(id);
        }
        public List<IdentityError> editarCategoria(int id, string nombre, string descripcion, Boolean estado, int funcion)
        {
            return categoriaFachada.editarCategoria(id, nombre, descripcion, estado, funcion);
        }
        
        public List<IdentityError> guardarCategoria(string nombre, string descripcion, string estado)
        {
            return categoriaFachada.guardarCategoria(nombre,descripcion,estado);
        }
     
    }
}

SistemaAC/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaAC.Data;
using SistemaAC.Models;
using SistemaAC.ModelsClass;
using SistemaAC.Negocio.Curso.Fachada;

namespace SistemaAC.Controllers
{
    public class CursosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ICursoFachada cursoFachada;

        public CursosController(ApplicationDbContext context)
        {
            _context = context;
            cursoFachada = new CursoFachada(context);
        }

        // GET: Cursos
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public List<Categoria> getCategorias()
        {
            return cursoFachada.getCategorias();
        }
        public List<IdentityError> agregarCurso(int id, string nombre, string descripcion, byte creditos, byte horas, decimal costo, Boolean estado, int categoria, string funcion)
        {
            return cursoFachada.agregarCurso(id, nombre, descripcion, creditos, horas, costo, estado, categoria, funcion);
        }
        public List<object[]> filtrarCurso(int numPagina, string valor, string order, int funcion)
        {
            return cursoFachada.filtrarCurso(numPagina, valor, order, funcion);
        }
        public List<Curso> getCursos(int id)
        {
            return cursoFachada.getCursos(id);
        }
        public List<IdentityError> editarCurso(int id, string nombre, string descripcion, byte creditos, byte horas, decimal costo, Boolean estado, int categoria, int funcion)
        {
            return cursoFachada.editarCurso(id, nombre, descripcion, creditos, horas, costo, estado, categoria, funcion);
        }
        public List<Instructor> getInstructors()
        {
            return cursoFachada.getInstructors();
        }
        public List<IdentityError> instructorCurso(List<Asignacion> asignacion)
        {
            return cursoFachada.instructorCurso(asignacion);
        }
    }
}

SistemaAC/Controllers/MisCursosController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SistemaAC.Data;
using SistemaAC.Models;
using SistemaAC.ModelsClass;
using SistemaAC.Negocio.MisCursos.Fachada;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaAC.Controllers
{
    public class MisCursosController:Controller
    {
        private readonly ApplicationDbContext _context;
        private IMisCursosFachada misCursosFachada;

        public MisCursosController(ApplicationDbContext context)
        {
            _context = context;
            misCursosFachada = new MisCursosFachada(context);
        }

        public IActionResult Index()
        {
            return View();
        }
        public List<object[]> filtrarMisCurso(int numPagina, string valor)
        {
            return misCursosFachada.filtrarMisCurso(numPagina, valor);
        }
        public List<Curso> getMisCursos(String query)
        {
            return misCursosFachada.getMisCursos(query);
        }
        public List<Estudiante> getMisEstudiantes(string query)
        {
            return misCursosFachada.getMisEstudiantes(query);
        }
        public List<Instructor> getMisDocentes(string query)
        {
            return misCursosFachada.getMisDocentes(query);
        }
        public List<IdentityError> actualizarMisCurso(String data)
        {
            var array = JArray.Parse(data);
            var dataCurso = array[0];
            DataCurso model = JsonConvert.DeserializeObject<DataCurso>(dataCurso.ToString());
            return misCursosFachada.actualizarMisCurso(model);
        }
   
    }
}

SistemaAC/Controllers/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SistemaAC.Data;
using SistemaAC.Negocio.Curso.Fachada;
using SistemaAC.Negocio.MisCursos.Fachada;

namespace SistemaAC.Controllers
{
    public class ReportesController : Controller
    {

        private ApplicationDbContext _context;
        private ICursoFachada cursoModels;
        private IMisCursosFachada inscripcion;

        public ReportesController(ApplicationDbContext context)
        {
            _context = context;
            cursoModels = new CursoFachada(context);
            inscripcion = new MisCursosFachada(context);
        }

        public IActionResult Index()
        {
            return View();
        }

        public List<object[]> reportesCursos(String valor, int numPagina, String order, int funcion)
        {
            String thead = "<tr>" +
                    "<th>Nombre</th>" +
                    "<th>Descripcion</th>" +
                    "<th>Creditos</th>" +
                    "<th>Horas</th>" +
                    "<th>Costo</th>" +
                    "<th>Estado</th>" +
                    "<th>Categoria</th>" +
                "</tr> ";
            object[] dataObj = { thead };
            var reportes = cursoModels.filtrarCurso(numPagina, valor, order, funcion);
            reportes.Add(dataObj);
            return reportes;
        }
        public int[] estadosCursos()
        {
            return cursoModels.estadosCursos();
        }

    }
}

SistemaAC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema Alumnos</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sistema Alumnos</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a></li>
                    <li><a asp-area="" asp-controller="Cursos" asp-action="Index">Cursos</a></li>
                    <li><a asp-area="" asp-controller="Estudiantes" asp-action="Index">Estudiantes</a></li>
                    <li><a asp-area="" asp-controller="Instructors" asp-action="Index">Instructor</a></li>
                    <li><a asp-area="" asp-controller="MisCursos" asp-action="Index">Mis Cursos</a></li>
                    <li><a asp-area="" asp-controller="Reportes" asp-action="Index">Reportes</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Sistema Alumnos Carlos Franceschi</p>
        </footer>
    </div>

    <environment include="Development">
        @*<script src="https://www.gstatic.com/charts/loader.js" asp-append-version="true"></script>*@
        <script src="~/js/loader.js" asp-append-version="true"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/typeahead.js" asp-append-version="true"></script>
        <script src="~/js/Categorias.js" asp-append-version="true"></script>
        <script src="~/js/Cursos.js" asp-append-version="true"></script>
        <script src="~/js/Estudiantes.js" asp-append-version="true"></script>
        <script src="~/js/Inscripciones.js" asp-append-version="true"></script>
        <script src="~/js/MisCursos.js" asp-append-version="true"></script>
        <script src="~/js/Graficas.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>